x-metadata:
  name: "Cypress Test Runner"
  description: "Cypress end-to-end test runner container. Executes test suites against the Jahia instance."
  group: "testing"
  requires:
    - service: "jahia"

services:
  cypress:
    image: "${JCLI_CYPRESS_IMAGE}"
    # https://github.com/cypress-io/cypress/issues/350
    ipc: host
    container_name: cypress
    hostname: cypress
    deploy:
      resources:
        limits:
          memory: 4gb
        reservations:
          memory: 2gb
    environment:
      MANIFEST: ${JCLI_CYPRESS_MANIFEST}
      JAHIA_URL: ${JCLI_CYPRESS_JAHIA_URL}
      JAHIA_USERNAME: ${JCLI_SECRET_CYPRESS_JAHIA_USERNAME}
      JAHIA_PASSWORD: ${JCLI_SECRET_CYPRESS_JAHIA_PASSWORD}
      SUPER_USER_PASSWORD: ${JCLI_SECRET_CYPRESS_JAHIA_SUPER_USER_PASSWORD}
      NEXUS_USERNAME: ${JCLI_SECRET_CYPRESS_NEXUS_USERNAME}
      NEXUS_PASSWORD: ${JCLI_SECRET_CYPRESS_NEXUS_PASSWORD}
      TESTS_PROFILE: ${TESTS_PROFILE}
