x-metadata:
  name: "Jahia Processing Node"
  description: "Core Jahia CMS processing server. Handles content authoring and background jobs."
  group: "core"
  requires: []

services:
  jahia:
    image: "${JAHIA_IMAGE:-jahia/jahia-ee:latest}"
    container_name: jahia
    hostname: jahia
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 4gb
    networks:
      - stack
    ports:
      - "8080:8080"
      - "8101:8101"
      - "8000:8000"
    extra_hosts:
      - jahia:127.0.0.1
    environment:
      jahia_cfg_karaf_remoteShellHost: 0.0.0.0
      DB_VENDOR: ${DB_VENDOR:-postgresql}
      DB_HOST: ${DB_HOST:-database}
      DB_NAME: ${DB_NAME:-jahia}
      DB_USER: ${DB_USER:-jahia}
      DB_PASS: ${DB_PASS:-jahia}
      JAHIA_LICENSE: ${JAHIA_LICENSE}
      SUPER_USER_PASSWORD: ${SUPER_USER_PASSWORD}
      CLUSTER_ENABLED: "${CLUSTER_ENABLED:-false}"
      PROCESSING_SERVER: "true"
      MAX_RAM_PERCENTAGE: ${MAX_RAM_PERCENTAGE:-95}
      RESTORE_MODULE_STATES: "false"
      NEXUS_USERNAME: ${NEXUS_USERNAME:-}
      NEXUS_PASSWORD: ${NEXUS_PASSWORD:-}
      JPDA: "true"
