x-metadata:
  name: "Jahia Browsing Node A"
  description: "First Jahia browsing/cluster node for read-only content delivery."
  optional: true

services:
  jahia-browsing-a:
    image: "${JCLI_JAHIA_IMAGE}"
    container_name: jahia-browsing-a
    hostname: jahia-browsing-a
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 6gb
        reservations:
          memory: 4gb
    networks:
      - stack
    ports:
      - "8081:8080"
      - "8102:8101"
    environment:
      jahia_cfg_karaf_remoteShellHost: 0.0.0.0
      DB_VENDOR: ${JCLI_JAHIA_DB_VENDOR}
      DB_HOST: ${JCLI_JAHIA_DB_HOST}
      DB_NAME: ${JCLI_JAHIA_DB_NAME}
      DB_USER: ${JCLI_SECRET_JAHIA_DB_USER}
      DB_PASS: ${JCLI_SECRET_JAHIA_DB_PASS}
      JAHIA_LICENSE: ${JCLI_JAHIA_LICENSE}
      SUPER_USER_PASSWORD: ${JCLI_SECRET_JAHIA_SUPER_USER_PASSWORD}
      CLUSTER_ENABLED: "true"
      PROCESSING_SERVER: "false"
      PROCESSING_HOST: "jahia"
      MAX_RAM_PERCENTAGE: 80
      RESTORE_MODULE_STATES: "false"
