x-metadata:
  name: "JCustomer Node A"
  description: "JCustomer Cluster Node A"
  group: "jcustomer"
  requires: []

services:
  jcustomer:
    image: "${JCLI_JCUSTOMER_IMAGE}"
    container_name: jcustomer
    hostname: jcustomer.jahia.net
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 3gb
        reservations:
          memory: 2gb
    networks:
      - stack:
        ipv4_address: 172.24.24.100
    ports:
      - 8181:8181
      - 9443:9443
      - 5005:5005
      - 8102:8102
    environment:
      UNOMI_ELASTICSEARCH_ADDRESSES: elasticsearch:9200
      UNOMI_ELASTICSEARCH_CLUSTERNAME: docker-cluster
      UNOMI_ELASTICSEARCH_USERNAME: ${JCLI_SECRET_ELASTICSEARCH_ELASTIC_USERNAME}
      UNOMI_ELASTICSEARCH_PASSWORD: ${JCLI_SECRET_ELASTICSEARCH_ELASTIC_PASSWORD}
      UNOMI_CLUSTER_PUBLIC_ADDRESS: https://jcustomer.jahia.net:8181
      UNOMI_CLUSTER_INTERNAL_ADDRESS: https://jcustomer.jahia.net:9443
      JAVA_MAX_MEM: 2G
      UNOMI_ROOT_PASSWORD: ${JCLI_SECRET_JCUSTOMER_UNOMI_ROOT_PASSWORD}
      UNOMI_HAZELCAST_TCPIP_MEMBERS: 172.24.24.100-102
      UNOMI_THIRDPARTY_PROVIDER1_KEY: 670c26d1cc413346c3b2fd9ce65dab41
      UNOMI_THIRDPARTY_PROVIDER1_IPADDRESSES: 172.24.24.0/24,::1,127.0.0.1
      KARAF_OPTS: "-Dunomi.autoStart=true"
      MAXMIND_KEY: ${JCLI_SECRET_JCUSTOMER_MAXMIND_KEY}
      JCUSTOMER_DEBUG: true
