x-metadata:
  name: "Kibana"
  description: "Kibana dashboard for Elasticsearch monitoring and data visualization."
  group: "search"
  requires:
    - service: "elasticsearch"

services:
  kibana:
    image: "${KIBANA_IMAGE:-docker.elastic.co/kibana/kibana:8.14.0}"
    container_name: kibana
    hostname: kibana
    deploy:
      resources:
        limits:
          memory: 2gb
    ports:
      - "5601:5601"
    networks:
      - stack
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      xpack.security.enabled: "true"
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: ${SUPER_USER_PASSWORD}
